### PR TITLE
Fix constant optimization and fused instruction

### LINKED ISSUE #228: Attempt to add new fusion instruction leads to error
The PR #227 introduced some bugs. Since the CI/CD for the compliance tests didn't run on the commit. This annoys contributors like me because they may not realize that the error for passing the compliance test doesn't come from themselves at first glance.

image

The problem can be reproduced by running the compliance tests with `.ci/riscv-tests.sh` on the local side. As you can see, there's a segmentation fault which didn't happen on the commit before #227.  Also, on this action job(https://github.com/sysprog21/rv32emu/actions/runs/6290355606/job/17077685558) I make sure that the PR does have some problems, but it still gets merged to the master branch.

image

### PR DESCRIPTION
**Pull request by qwe661234**
1. Fix tailcall updating in fused instructions
2. Fix errors in constant optimization

Close: #228

### CODE REVIEW

File: src/emulate.c [hunk 1]
```diff
@@ -935,21 +936,22 @@ static void match_pattern(block_t *block)
                 ir->rs2 = next_ir->rd;
                 ir->rs1 = next_ir->rs2;
                 ir->impl = dispatch_table[ir->opcode];
-            } else {
+                ir->tailcall = next_ir->tailcall;
+            } else if (next_ir->opcode == rv_insn_lui) {
```
Comment (jserv) [inline src/emulate.c]: Is it possible to rewrite with switch-case statements for readability?

File: src/emulate.c [hunk 2]
```diff
@@ -918,41 +918,40 @@ static void match_pattern(block_t *block)
...
-                 * same as the source register 1 of the next instruction ADD.
-                 */
-                ir->opcode = rv_insn_fuse2;
-                ir->rs2 = next_ir->rd;
-                ir->rs1 = next_ir->rs2;
-                ir->impl = dispatch_table[ir->opcode];
-            } else {
+            switch (next_ir->opcode) {
+            case rv_insn_add:
+                if (ir->rd == next_ir->rs2) {
```
Comment (jserv) [inline src/emulate.c]: Can you avoid duplicating code in L923 to L934?

File: src/rv32_constopt.c [hunk 3]
```diff
@@ -757,7 +756,7 @@ CONSTOPT(csw, {})
 CONSTOPT(caddi, {
     if (constopt_info->is_constant[ir->rd]) {
         constopt_info->is_constant[ir->rd] = true;
```
Comment (RinHizakura) [inline src/rv32_constopt.c]: It may not relate directly in this PR, but I'm Not sure why should we assign `true` to a variable that we have already known as true in the if statement. For example:

 ```cpp
 if (constopt_info->is_constant[ir->rd]) {
        constopt_info->is_constant[ir->rd] = true;
```

It just looks like `constopt_info->is_constant[ir->rd] = true` is a redundant operation. Or do I miss something?

Comment (qwe661234) [reply src/rv32_constopt.c]: Yes, it is redundant, I'll remove it.

File: src/rv32_constopt.c [hunk 4]
```diff
@@ -815,9 +812,9 @@ CONSTOPT(clui, {
...
 CONSTOPT(csrli, {
     if (constopt_info->is_constant[ir->rs1]) {
-        constopt_info->is_constant[ir->rs1] = true;
         ir->imm = constopt_info->const_val[ir->rs1] >> ir->shamt;
-        constopt_info->const_val[ir->rd] = ir->imm;
+        constopt_info->const_val[ir->rs1] = ir->imm;
+        ir->rd = ir->rs1;
         ir->opcode = rv_insn_clui;
         ir->impl = dispatch_table[ir->opcode];
     } else
```
Comment (RinHizakura) [inline src/rv32_constopt.c]: How about those else cases here? A statement like `constopt_info->is_constant[ir->rs1] = false` here should also be redundant.

**Comment by RinHizakura** [comment]
Since it now looks great on the architectural test, I am fine with the change now. Thanks!

File: src/rv32_constopt.c (hunk 4 above)
Comment (qwe661234) [reply src/rv32_constopt.c]: Yes, it is redundant, I'll remove it.
